-- ============================================================
-- ERP EDUCATIVO INTEGRAL
-- FASE 1: NUCLEO INSTITUCIONAL, IDENTIDAD, SEGURIDAD,
-- CONFIGURACION, CATALOGOS, PERIODOS Y AUDITORIA
-- Motor de base de datos: PostgreSQL
-- ============================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS erp;
SET search_path TO erp;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- TIPOS ENUMERADOS BASE
-- ============================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_general') THEN
        CREATE TYPE erp.estado_general AS ENUM ('ACTIVO', 'INACTIVO', 'ELIMINADO');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_usuario') THEN
        CREATE TYPE erp.estado_usuario AS ENUM ('ACTIVO', 'INACTIVO', 'BLOQUEADO', 'PENDIENTE');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_identificacion') THEN
        CREATE TYPE erp.tipo_identificacion AS ENUM ('CEDULA', 'RUC', 'PASAPORTE', 'EXTRANJERO', 'OTRO');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_periodo_lectivo') THEN
        CREATE TYPE erp.estado_periodo_lectivo AS ENUM ('PLANIFICADO', 'ACTIVO', 'CERRADO', 'ANULADO');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ambito_configuracion') THEN
        CREATE TYPE erp.ambito_configuracion AS ENUM ('GLOBAL', 'INSTITUCION', 'SEDE', 'PERIODO', 'MODULO', 'USUARIO');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_dato_configuracion') THEN
        CREATE TYPE erp.tipo_dato_configuracion AS ENUM ('TEXTO', 'NUMERO', 'DECIMAL', 'BOOLEANO', 'FECHA', 'HORA', 'JSON', 'LISTA', 'ARCHIVO', 'COLOR');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_catalogo') THEN
        CREATE TYPE erp.tipo_catalogo AS ENUM ('SISTEMA', 'INSTITUCIONAL', 'OPERATIVO');
    END IF;
END $$;

-- ============================================================
-- FUNCION TRANSVERSAL updated_at
-- ============================================================

CREATE OR REPLACE FUNCTION erp.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- TABLAS BASE
-- ============================================================

CREATE TABLE IF NOT EXISTS erp.persona (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_identificacion erp.tipo_identificacion NOT NULL,
    identificacion      VARCHAR(30) NOT NULL,
    nombres             VARCHAR(120) NOT NULL,
    apellidos           VARCHAR(120) NOT NULL,
    fecha_nacimiento    DATE,
    genero              VARCHAR(30),
    correo              VARCHAR(150),
    telefono            VARCHAR(50),
    direccion           TEXT,
    estado              erp.estado_general NOT NULL DEFAULT 'ACTIVO',
    metadata            JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_by          BIGINT,
    CONSTRAINT uq_persona_identificacion UNIQUE (tipo_identificacion, identificacion)
);

CREATE INDEX IF NOT EXISTS idx_persona_nombres ON erp.persona (nombres, apellidos);
CREATE INDEX IF NOT EXISTS idx_persona_correo ON erp.persona (correo);
CREATE INDEX IF NOT EXISTS idx_persona_metadata_gin ON erp.persona USING GIN (metadata);

DROP TRIGGER IF EXISTS trg_persona_updated_at ON erp.persona;
CREATE TRIGGER trg_persona_updated_at
BEFORE UPDATE ON erp.persona
FOR EACH ROW EXECUTE FUNCTION erp.set_updated_at();

CREATE TABLE IF NOT EXISTS erp.institucion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(30) NOT NULL,
    nombre              VARCHAR(200) NOT NULL,
    razon_social        VARCHAR(200),
    tipo_identificacion erp.tipo_identificacion,
    identificacion      VARCHAR(30),
    direccion           TEXT,
    telefono            VARCHAR(50),
    correo              VARCHAR(150),
    sitio_web           VARCHAR(200),
    logo_url            TEXT,
    color_primario      VARCHAR(20),
    estado              erp.estado_general NOT NULL DEFAULT 'ACTIVO',
    metadata            JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_by          BIGINT,
    CONSTRAINT uq_institucion_codigo UNIQUE (codigo)
);

CREATE INDEX IF NOT EXISTS idx_institucion_metadata_gin ON erp.institucion USING GIN (metadata);

DROP TRIGGER IF EXISTS trg_institucion_updated_at ON erp.institucion;
CREATE TRIGGER trg_institucion_updated_at
BEFORE UPDATE ON erp.institucion
FOR EACH ROW EXECUTE FUNCTION erp.set_updated_at();

CREATE TABLE IF NOT EXISTS erp.sede (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id  BIGINT NOT NULL REFERENCES erp.institucion(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    codigo          VARCHAR(30) NOT NULL,
    nombre          VARCHAR(150) NOT NULL,
    direccion       TEXT,
    telefono        VARCHAR(50),
    correo          VARCHAR(150),
    estado          erp.estado_general NOT NULL DEFAULT 'ACTIVO',
    metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_by      BIGINT,
    CONSTRAINT uq_sede_institucion_codigo UNIQUE (institucion_id, codigo)
);

CREATE INDEX IF NOT EXISTS idx_sede_institucion ON erp.sede (institucion_id);

DROP TRIGGER IF EXISTS trg_sede_updated_at ON erp.sede;
CREATE TRIGGER trg_sede_updated_at
BEFORE UPDATE ON erp.sede
FOR EACH ROW EXECUTE FUNCTION erp.set_updated_at();

CREATE TABLE IF NOT EXISTS erp.periodo_lectivo (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id  BIGINT NOT NULL REFERENCES erp.institucion(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    codigo          VARCHAR(30) NOT NULL,
    nombre          VARCHAR(150) NOT NULL,
    fecha_inicio    DATE NOT NULL,
    fecha_fin       DATE NOT NULL,
    estado          erp.estado_periodo_lectivo NOT NULL DEFAULT 'PLANIFICADO',
    es_actual       BOOLEAN NOT NULL DEFAULT FALSE,
    metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_by      BIGINT,
    CONSTRAINT uq_periodo_institucion_codigo UNIQUE (institucion_id, codigo),
    CONSTRAINT chk_periodo_fechas CHECK (fecha_fin >= fecha_inicio)
);

CREATE INDEX IF NOT EXISTS idx_periodo_institucion ON erp.periodo_lectivo (institucion_id);
CREATE INDEX IF NOT EXISTS idx_periodo_estado ON erp.periodo_lectivo (estado);
CREATE UNIQUE INDEX IF NOT EXISTS uq_periodo_actual_por_institucion
ON erp.periodo_lectivo (institucion_id)
WHERE es_actual = TRUE;

DROP TRIGGER IF EXISTS trg_periodo_lectivo_updated_at ON erp.periodo_lectivo;
CREATE TRIGGER trg_periodo_lectivo_updated_at
BEFORE UPDATE ON erp.periodo_lectivo
FOR EACH ROW EXECUTE FUNCTION erp.set_updated_at();

CREATE TABLE IF NOT EXISTS erp.catalogo (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT REFERENCES erp.institucion(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    codigo      VARCHAR(60) NOT NULL,
    nombre      VARCHAR(150) NOT NULL,
    descripcion TEXT,
    tipo        erp.tipo_catalogo NOT NULL DEFAULT 'OPERATIVO',
    editable    BOOLEAN NOT NULL DEFAULT TRUE,
    estado      erp.estado_general NOT NULL DEFAULT 'ACTIVO',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_by  BIGINT,
    CONSTRAINT chk_catalogo_sistema_global CHECK (tipo <> 'SISTEMA' OR institucion_id IS NULL),
    CONSTRAINT chk_catalogo_institucional_contexto CHECK (tipo <> 'INSTITUCIONAL' OR institucion_id IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_catalogo_codigo_global
ON erp.catalogo (codigo)
WHERE institucion_id IS NULL AND estado <> 'ELIMINADO';

CREATE UNIQUE INDEX IF NOT EXISTS uq_catalogo_codigo_institucion
ON erp.catalogo (institucion_id, codigo)
WHERE institucion_id IS NOT NULL AND estado <> 'ELIMINADO';

DROP TRIGGER IF EXISTS trg_catalogo_updated_at ON erp.catalogo;
CREATE TRIGGER trg_catalogo_updated_at
BEFORE UPDATE ON erp.catalogo
FOR EACH ROW EXECUTE FUNCTION erp.set_updated_at();

CREATE TABLE IF NOT EXISTS erp.catalogo_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalogo_id BIGINT NOT NULL REFERENCES erp.catalogo(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    codigo      VARCHAR(60) NOT NULL,
    nombre      VARCHAR(150) NOT NULL,
    descripcion TEXT,
    valor       JSONB NOT NULL DEFAULT '{}'::jsonb,
    es_base     BOOLEAN NOT NULL DEFAULT FALSE,
    orden       INTEGER NOT NULL DEFAULT 0,
    estado      erp.estado_general NOT NULL DEFAULT 'ACTIVO',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_by  BIGINT,
    CONSTRAINT uq_catalogo_item_codigo UNIQUE (catalogo_id, codigo)
);

CREATE INDEX IF NOT EXISTS idx_catalogo_item_catalogo ON erp.catalogo_item (catalogo_id);
CREATE INDEX IF NOT EXISTS idx_catalogo_item_valor_gin ON erp.catalogo_item USING GIN (valor);

DROP TRIGGER IF EXISTS trg_catalogo_item_updated_at ON erp.catalogo_item;
CREATE TRIGGER trg_catalogo_item_updated_at
BEFORE UPDATE ON erp.catalogo_item
FOR EACH ROW EXECUTE FUNCTION erp.set_updated_at();

CREATE TABLE IF NOT EXISTS erp.usuario (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id             BIGINT NOT NULL REFERENCES erp.persona(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    username               VARCHAR(80) NOT NULL,
    email_acceso           VARCHAR(150),
    password_hash          TEXT NOT NULL,
    estado                 erp.estado_usuario NOT NULL DEFAULT 'PENDIENTE',
    ultimo_acceso          TIMESTAMPTZ,
    debe_cambiar_clave     BOOLEAN NOT NULL DEFAULT TRUE,
    intentos_fallidos      INTEGER NOT NULL DEFAULT 0,
    bloqueado_hasta        TIMESTAMPTZ,
    metadata               JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by             BIGINT,
    updated_by             BIGINT,
    CONSTRAINT uq_usuario_persona UNIQUE (persona_id),
    CONSTRAINT uq_usuario_username UNIQUE (username),
    CONSTRAINT uq_usuario_email UNIQUE (email_acceso)
);

CREATE INDEX IF NOT EXISTS idx_usuario_estado ON erp.usuario (estado);
CREATE INDEX IF NOT EXISTS idx_usuario_metadata_gin ON erp.usuario USING GIN (metadata);

DROP TRIGGER IF EXISTS trg_usuario_updated_at ON erp.usuario;
CREATE TRIGGER trg_usuario_updated_at
BEFORE UPDATE ON erp.usuario
FOR EACH ROW EXECUTE FUNCTION erp.set_updated_at();

CREATE TABLE IF NOT EXISTS erp.parametro_configuracion (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(100) NOT NULL,
    nombre          VARCHAR(150) NOT NULL,
    descripcion     TEXT,
    tipo_dato       erp.tipo_dato_configuracion NOT NULL,
    valor           JSONB NOT NULL DEFAULT 'null'::jsonb,
    ambito          erp.ambito_configuracion NOT NULL DEFAULT 'GLOBAL',
    institucion_id  BIGINT REFERENCES erp.institucion(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    sede_id         BIGINT REFERENCES erp.sede(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    periodo_id      BIGINT REFERENCES erp.periodo_lectivo(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    modulo          VARCHAR(80),
    usuario_id      BIGINT REFERENCES erp.usuario(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    editable        BOOLEAN NOT NULL DEFAULT TRUE,
    version         INTEGER NOT NULL DEFAULT 1,
    fecha_inicio    DATE,
    fecha_fin       DATE,
    estado          erp.estado_general NOT NULL DEFAULT 'ACTIVO',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_by      BIGINT,
    CONSTRAINT chk_parametro_vigencia CHECK (fecha_fin IS NULL OR fecha_inicio IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE INDEX IF NOT EXISTS idx_parametro_codigo ON erp.parametro_configuracion (codigo);
CREATE INDEX IF NOT EXISTS idx_parametro_ambito ON erp.parametro_configuracion (ambito);
CREATE INDEX IF NOT EXISTS idx_parametro_valor_gin ON erp.parametro_configuracion USING GIN (valor);

CREATE UNIQUE INDEX IF NOT EXISTS uq_param_global
ON erp.parametro_configuracion (codigo)
WHERE ambito = 'GLOBAL' AND institucion_id IS NULL AND sede_id IS NULL AND periodo_id IS NULL AND modulo IS NULL AND usuario_id IS NULL AND estado <> 'ELIMINADO';

CREATE UNIQUE INDEX IF NOT EXISTS uq_param_institucion
ON erp.parametro_configuracion (codigo, institucion_id)
WHERE ambito = 'INSTITUCION' AND institucion_id IS NOT NULL AND sede_id IS NULL AND periodo_id IS NULL AND modulo IS NULL AND usuario_id IS NULL AND estado <> 'ELIMINADO';

CREATE UNIQUE INDEX IF NOT EXISTS uq_param_sede
ON erp.parametro_configuracion (codigo, institucion_id, sede_id)
WHERE ambito = 'SEDE' AND institucion_id IS NOT NULL AND sede_id IS NOT NULL AND periodo_id IS NULL AND modulo IS NULL AND usuario_id IS NULL AND estado <> 'ELIMINADO';

CREATE UNIQUE INDEX IF NOT EXISTS uq_param_periodo
ON erp.parametro_configuracion (codigo, institucion_id, periodo_id)
WHERE ambito = 'PERIODO' AND institucion_id IS NOT NULL AND periodo_id IS NOT NULL AND sede_id IS NULL AND modulo IS NULL AND usuario_id IS NULL AND estado <> 'ELIMINADO';

CREATE UNIQUE INDEX IF NOT EXISTS uq_param_modulo
ON erp.parametro_configuracion (codigo, institucion_id, modulo)
WHERE ambito = 'MODULO' AND institucion_id IS NOT NULL AND modulo IS NOT NULL AND sede_id IS NULL AND periodo_id IS NULL AND usuario_id IS NULL AND estado <> 'ELIMINADO';

CREATE UNIQUE INDEX IF NOT EXISTS uq_param_usuario
ON erp.parametro_configuracion (codigo, usuario_id)
WHERE ambito = 'USUARIO' AND usuario_id IS NOT NULL AND estado <> 'ELIMINADO';

DROP TRIGGER IF EXISTS trg_parametro_configuracion_updated_at ON erp.parametro_configuracion;
CREATE TRIGGER trg_parametro_configuracion_updated_at
BEFORE UPDATE ON erp.parametro_configuracion
FOR EACH ROW EXECUTE FUNCTION erp.set_updated_at();

CREATE TABLE IF NOT EXISTS erp.rol (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(60) NOT NULL,
    nombre      VARCHAR(120) NOT NULL,
    descripcion TEXT,
    es_sistema  BOOLEAN NOT NULL DEFAULT FALSE,
    estado      erp.estado_general NOT NULL DEFAULT 'ACTIVO',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_by  BIGINT,
    CONSTRAINT uq_rol_codigo UNIQUE (codigo)
);

DROP TRIGGER IF EXISTS trg_rol_updated_at ON erp.rol;
CREATE TRIGGER trg_rol_updated_at
BEFORE UPDATE ON erp.rol
FOR EACH ROW EXECUTE FUNCTION erp.set_updated_at();

CREATE TABLE IF NOT EXISTS erp.permiso (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(120) NOT NULL,
    modulo      VARCHAR(80) NOT NULL,
    recurso     VARCHAR(80) NOT NULL,
    accion      VARCHAR(80) NOT NULL,
    descripcion TEXT,
    estado      erp.estado_general NOT NULL DEFAULT 'ACTIVO',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_by  BIGINT,
    CONSTRAINT uq_permiso_codigo UNIQUE (codigo),
    CONSTRAINT uq_permiso_mod_rec_acc UNIQUE (modulo, recurso, accion)
);

CREATE INDEX IF NOT EXISTS idx_permiso_modulo ON erp.permiso (modulo);

DROP TRIGGER IF EXISTS trg_permiso_updated_at ON erp.permiso;
CREATE TRIGGER trg_permiso_updated_at
BEFORE UPDATE ON erp.permiso
FOR EACH ROW EXECUTE FUNCTION erp.set_updated_at();

CREATE TABLE IF NOT EXISTS erp.usuario_rol (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      BIGINT NOT NULL REFERENCES erp.usuario(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    rol_id          BIGINT NOT NULL REFERENCES erp.rol(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    institucion_id  BIGINT REFERENCES erp.institucion(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    sede_id         BIGINT REFERENCES erp.sede(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    periodo_id      BIGINT REFERENCES erp.periodo_lectivo(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    fecha_inicio    DATE,
    fecha_fin       DATE,
    estado          erp.estado_general NOT NULL DEFAULT 'ACTIVO',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_by      BIGINT,
    CONSTRAINT chk_usuario_rol_fechas CHECK (fecha_fin IS NULL OR fecha_inicio IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE INDEX IF NOT EXISTS idx_usuario_rol_usuario ON erp.usuario_rol (usuario_id);
CREATE INDEX IF NOT EXISTS idx_usuario_rol_rol ON erp.usuario_rol (rol_id);
CREATE INDEX IF NOT EXISTS idx_usuario_rol_contexto ON erp.usuario_rol (institucion_id, sede_id, periodo_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_usuario_rol_global_activo
ON erp.usuario_rol (usuario_id, rol_id)
WHERE institucion_id IS NULL AND sede_id IS NULL AND periodo_id IS NULL AND estado = 'ACTIVO';

CREATE UNIQUE INDEX IF NOT EXISTS uq_usuario_rol_institucion_activo
ON erp.usuario_rol (usuario_id, rol_id, institucion_id)
WHERE institucion_id IS NOT NULL AND sede_id IS NULL AND periodo_id IS NULL AND estado = 'ACTIVO';

CREATE UNIQUE INDEX IF NOT EXISTS uq_usuario_rol_sede_activo
ON erp.usuario_rol (usuario_id, rol_id, institucion_id, sede_id)
WHERE institucion_id IS NOT NULL AND sede_id IS NOT NULL AND periodo_id IS NULL AND estado = 'ACTIVO';

CREATE UNIQUE INDEX IF NOT EXISTS uq_usuario_rol_periodo_activo
ON erp.usuario_rol (usuario_id, rol_id, institucion_id, periodo_id)
WHERE institucion_id IS NOT NULL AND periodo_id IS NOT NULL AND sede_id IS NULL AND estado = 'ACTIVO';

CREATE UNIQUE INDEX IF NOT EXISTS uq_usuario_rol_sede_periodo_activo
ON erp.usuario_rol (usuario_id, rol_id, institucion_id, sede_id, periodo_id)
WHERE institucion_id IS NOT NULL AND sede_id IS NOT NULL AND periodo_id IS NOT NULL AND estado = 'ACTIVO';

DROP TRIGGER IF EXISTS trg_usuario_rol_updated_at ON erp.usuario_rol;
CREATE TRIGGER trg_usuario_rol_updated_at
BEFORE UPDATE ON erp.usuario_rol
FOR EACH ROW EXECUTE FUNCTION erp.set_updated_at();

CREATE TABLE IF NOT EXISTS erp.rol_permiso (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id      BIGINT NOT NULL REFERENCES erp.rol(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    permiso_id  BIGINT NOT NULL REFERENCES erp.permiso(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    estado      erp.estado_general NOT NULL DEFAULT 'ACTIVO',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_by  BIGINT,
    CONSTRAINT uq_rol_permiso UNIQUE (rol_id, permiso_id)
);

CREATE INDEX IF NOT EXISTS idx_rol_permiso_rol ON erp.rol_permiso (rol_id);
CREATE INDEX IF NOT EXISTS idx_rol_permiso_permiso ON erp.rol_permiso (permiso_id);

DROP TRIGGER IF EXISTS trg_rol_permiso_updated_at ON erp.rol_permiso;
CREATE TRIGGER trg_rol_permiso_updated_at
BEFORE UPDATE ON erp.rol_permiso
FOR EACH ROW EXECUTE FUNCTION erp.set_updated_at();

CREATE TABLE IF NOT EXISTS erp.sesion_usuario (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id      BIGINT NOT NULL REFERENCES erp.usuario(id) ON UPDATE CASCADE ON DELETE CASCADE,
    token_hash      TEXT NOT NULL,
    ip              INET,
    user_agent      TEXT,
    fecha_inicio    TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_expira    TIMESTAMPTZ NOT NULL,
    fecha_cierre    TIMESTAMPTZ,
    estado          VARCHAR(30) NOT NULL DEFAULT 'ACTIVA',
    metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT chk_sesion_fechas CHECK (fecha_expira > fecha_inicio)
);

CREATE INDEX IF NOT EXISTS idx_sesion_usuario ON erp.sesion_usuario (usuario_id);
CREATE INDEX IF NOT EXISTS idx_sesion_estado ON erp.sesion_usuario (estado);
CREATE INDEX IF NOT EXISTS idx_sesion_expira ON erp.sesion_usuario (fecha_expira);

CREATE TABLE IF NOT EXISTS erp.auditoria (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha            TIMESTAMPTZ NOT NULL DEFAULT now(),
    usuario_id       BIGINT REFERENCES erp.usuario(id) ON UPDATE CASCADE ON DELETE SET NULL,
    persona_id       BIGINT REFERENCES erp.persona(id) ON UPDATE CASCADE ON DELETE SET NULL,
    institucion_id   BIGINT REFERENCES erp.institucion(id) ON UPDATE CASCADE ON DELETE SET NULL,
    modulo           VARCHAR(80) NOT NULL,
    entidad          VARCHAR(120) NOT NULL,
    entidad_id       VARCHAR(120),
    accion           VARCHAR(80) NOT NULL,
    valor_anterior   JSONB,
    valor_nuevo      JSONB,
    ip               INET,
    user_agent       TEXT,
    motivo           TEXT,
    metadata         JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_auditoria_fecha ON erp.auditoria (fecha);
CREATE INDEX IF NOT EXISTS idx_auditoria_usuario ON erp.auditoria (usuario_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_modulo_entidad ON erp.auditoria (modulo, entidad);
CREATE INDEX IF NOT EXISTS idx_auditoria_metadata_gin ON erp.auditoria USING GIN (metadata);

-- ============================================================
-- DATOS INICIALES
-- ============================================================

INSERT INTO erp.catalogo (codigo, nombre, descripcion, tipo, editable)
VALUES
    ('TIPO_IDENTIFICACION', 'Tipos de identificación', 'Catálogo de tipos de identificación usados por personas e instituciones.', 'SISTEMA', FALSE),
    ('GENERO', 'Género', 'Catálogo básico de género.', 'OPERATIVO', TRUE),
    ('PARENTESCO', 'Parentesco', 'Relaciones familiares entre estudiante y representante.', 'OPERATIVO', TRUE),
    ('ESTADO_CIVIL', 'Estado civil', 'Estados civiles de personas.', 'OPERATIVO', TRUE)
ON CONFLICT DO NOTHING;

INSERT INTO erp.catalogo_item (catalogo_id, codigo, nombre, es_base, orden)
SELECT c.id, v.codigo, v.nombre, TRUE, v.orden
FROM erp.catalogo c
JOIN (
    VALUES
        ('CEDULA', 'Cédula', 1),
        ('RUC', 'RUC', 2),
        ('PASAPORTE', 'Pasaporte', 3),
        ('EXTRANJERO', 'Documento extranjero', 4),
        ('OTRO', 'Otro', 99)
) AS v(codigo, nombre, orden) ON TRUE
WHERE c.codigo = 'TIPO_IDENTIFICACION'
ON CONFLICT (catalogo_id, codigo) DO NOTHING;

INSERT INTO erp.rol (codigo, nombre, descripcion, es_sistema)
VALUES
    ('SUPERADMIN', 'Superadministrador', 'Administrador global del ERP.', TRUE),
    ('ADMIN_INSTITUCION', 'Administrador institucional', 'Administrador de una institución educativa.', TRUE),
    ('RECTOR', 'Rector / Autoridad', 'Autoridad institucional.', TRUE),
    ('SECRETARIA', 'Secretaría', 'Gestión de inscripción, matrícula y documentos académicos.', TRUE),
    ('DOCENTE', 'Docente', 'Docente con asignaciones académicas.', TRUE),
    ('REPRESENTANTE', 'Representante', 'Representante académico, legal o financiero.', TRUE),
    ('ESTUDIANTE', 'Estudiante', 'Usuario estudiante.', TRUE),
    ('FINANCIERO', 'Financiero', 'Gestión financiera educativa.', TRUE),
    ('DECE', 'DECE / Bienestar', 'Gestión de acompañamiento estudiantil.', TRUE)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO erp.permiso (codigo, modulo, recurso, accion, descripcion)
VALUES
    ('sistema.configurar', 'sistema', 'configuracion', 'configurar', 'Administrar configuración general del sistema.'),
    ('persona.ver', 'nucleo', 'persona', 'ver', 'Ver personas.'),
    ('persona.crear', 'nucleo', 'persona', 'crear', 'Crear personas.'),
    ('persona.editar', 'nucleo', 'persona', 'editar', 'Editar personas.'),
    ('usuario.ver', 'seguridad', 'usuario', 'ver', 'Ver usuarios.'),
    ('usuario.crear', 'seguridad', 'usuario', 'crear', 'Crear usuarios.'),
    ('usuario.editar', 'seguridad', 'usuario', 'editar', 'Editar usuarios.'),
    ('rol.administrar', 'seguridad', 'rol', 'administrar', 'Administrar roles y permisos.'),
    ('periodo.ver', 'nucleo', 'periodo', 'ver', 'Ver periodos lectivos.'),
    ('periodo.administrar', 'nucleo', 'periodo', 'administrar', 'Administrar periodos lectivos.')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO erp.rol_permiso (rol_id, permiso_id)
SELECT r.id, p.id
FROM erp.rol r
CROSS JOIN erp.permiso p
WHERE r.codigo = 'SUPERADMIN'
ON CONFLICT (rol_id, permiso_id) DO NOTHING;

INSERT INTO erp.parametro_configuracion
    (codigo, nombre, descripcion, tipo_dato, valor, ambito, editable)
VALUES
    ('sistema.nombre', 'Nombre del sistema', 'Nombre visible del ERP.', 'TEXTO', to_jsonb('ERP Educativo Integral'::text), 'GLOBAL', TRUE),
    ('seguridad.intentos_login', 'Intentos fallidos permitidos', 'Número de intentos fallidos antes de bloqueo.', 'NUMERO', to_jsonb(5), 'GLOBAL', TRUE),
    ('seguridad.duracion_sesion_minutos', 'Duración de sesión', 'Duración de sesión en minutos.', 'NUMERO', to_jsonb(120), 'GLOBAL', TRUE),
    ('ia.habilitada', 'IA institucional habilitada', 'Activa o desactiva la capa de IA asistiva.', 'BOOLEANO', to_jsonb(true), 'GLOBAL', TRUE)
ON CONFLICT DO NOTHING;

COMMIT;
